Updated workflow

diff --git a/.github/workflows/custom-image-builder.yml b/.github/workflows/custom-image-builder.yml
--- a/.github/workflows/custom-image-builder.yml
+++ b/.github/workflows/custom-image-builder.yml
@@ -1,7 +1,7 @@
 name: Run Integration Test and Build Custom Amazon Machine Image (AMI) Using Packer
 
 on:
-  pull_request:
+  push:
     branches:
       - main
 
@@ -51,3 +51,32 @@ jobs:
           AMI_ID=$(awk -F, '/artifact,0,id/ {print $6}' packer.log | cut -d: -f2)
           echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT
           echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
+
+      - name: Set the Environment
+        id: determine-environment
+        run: |
+          if [ "${{ env.IS_DEV_ENVIRONMENT }}" == "true" ] && [ "${{ env.IS_DEMO_ENVIRONMENT }}" == "true" ]; then
+            echo "ENVIRONMENTS=dev,demo" >> $GITHUB_ENV
+          elif [ "${{ env.IS_DEV_ENVIRONMENT }}" == "true" ]; then
+            echo "ENVIRONMENTS=dev" >> $GITHUB_ENV
+          elif [ "${{ env.IS_DEMO_ENVIRONMENT }}" == "true" ]; then
+            echo "ENVIRONMENTS=demo" >> $GITHUB_ENV
+          else
+            echo "Error: No environment provided" >&2
+            exit 1
+          fi
+
+      - name: Configure DEV account AWS credentials
+        if: contains(env.ENVIRONMENTS, 'dev')
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Process dev environment
+        if: ${{ env.ENVIRONMENTS == 'dev' || env.ENVIRONMENTS == 'dev,demo' }}
+        run: |
+          echo "currently running in Dev Environment..."
+          echo "For now, the script will skip the deployment to the Dev environment"
+        
